#https://github.com/standardrb/standard

#fix: true
#parallel: true
format: progress
ruby_version: 2.6.10
default_ignores: false

ignore:
#file example
#  - 'some/file/in/particular.rb'
#  - 'a/whole/directory/**/*'
# rule example
#  - 'test/**/*':
#  - Layout/AlignHash
plugins:
  - standard-rails