version: "3.5"
services:
  app:
    build:
      context: .
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - itjobs_app_network
  postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - itjobs_app_network
volumes:
  postgres_data:
networks:
  itjobs_app_network: