version: "3.5"
services:
  app:
    build:
      context: .
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - itjobs_app_network
  postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - itjobs_app_network
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    ports:
      - 9200:9200
    volumes:
      - elasticsearch_data:/var/lib//elasticsearch/data
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=false
    networks:
      - itjobs_app_network
volumes:
  postgres_data:
  elasticsearch_data:
networks:
  itjobs_app_network: