default: &default
  adapter:  postgresql
  encoding: utf8
  database: itjobs
  host:     <%= ENV.fetch("POSTGRES_HOST") { 'localhost' } %>
  username: <%= ENV.fetch("POSTGRES_USER") { 'itjobs'} %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { 'itjobs'} %>
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: itjobs_dev
test:
  <<: *default
  database: itjobs_test
production:
  <<: *default
staging:
  <<: *default